apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-bian-employee-data-management
spec:
  selector:
    matchLabels:
      app: nodejs-bian-employee-data-management
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs-bian-employee-data-management
    spec:
      containers:
      - name: nodejs-bian-employee-data-management
        image: juliopari/nodejs-bian-employee-data-management:v1
        ports:
        - name: http
          containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-bian-employee-data-management
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: nodejs-bian-employee-data-management
